# Generated by Django 4.2.11 on 2026-02-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('COUNTRY_ADMIN', 'Country Admin'), ('COUNTRY_MEMBER', 'Country Member')], default='COUNTRY_MEMBER', max_length=20),
        ),
    ]
