# Generated by Django 4.1.5 on 2023-04-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("codename", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
                ("discount_percent", models.IntegerField()),
            ],
        ),
    ]
